FROM traefik:v2.4.9

ENV CBWXPROXY_ADMIN_PORT=8888 \
    CBWXPROXY_BEDROCK_ENABLE="false" \
    CBWXPROXY_BEDROCK_PORT=19132 \
    CBWXPROXY_JAVA_ENABLE="false" \
    CBWXPROXY_JAVA_PORT=25565

EXPOSE $CBWXPROXY_ADMIN_PORT
EXPOSE $CBWXPROXY_BEDROCK_PORT/udp
EXPOSE $CBWXPROXY_JAVA_PORT

ADD entrypoint.sh /